apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-vndprojects-com-tls
spec:
  secretName: kubernetes-vndprojects-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetes.vndprojects.com
  dnsNames:
    - kubernetes.vndprojects.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kubernetes.vndprojects.com
